---
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'spec/dummy/bin/*'

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/cocooned.gemspec'
    - 'spec/dummy/db/schema.rb'
    - 'spec/cocooned/**/*_spec.rb'
    - 'spec/shared_examples/**/*.rb'
